export const clinicProLandingData = {
  hero: {
    headline: 'Finish Your Consultation Notes in Under 1 Minute',
    subheadlines: [
      'Cut admin time – Stop Working Afterhours',
      'Zero setup – browser + QR code, record on your phone',
      'Built by a NZ GP, for NZ GPs – your feedback shapes each update',
    ],
    primaryCTA: 'Join First 30 GPs at NZ$ 30/mo (60% off)',
    secondaryCTA: 'Get Early Access',
    countdownText: 'First 30 spots',
  },

  metrics: [
    { value: '0', unit: 'hours', label: 'unpaid overtime' },
    { value: '100', unit: '%', label: 'present with patients' },
    { value: '∞', unit: 'time', label: 'reclaimed for life' },
  ],

  coreFeatures: [
    {
      title: 'Instant, Structured Notes',
      description: 'AI-generated SOAP notes in seconds, not minutes',
      icon: 'FileText',
    },
    {
      title: 'Reliable Transcription & Redaction',
      description: 'Accurate speech-to-text with automatic privacy protection',
      icon: 'Mic',
    },
    {
      title: 'You\'re in Charge',
      description: 'Full control over your notes with easy editing and approval',
      icon: 'Settings',
    },
    {
      title: 'Easy Consent & Data Safety',
      description: 'Simple patient consent with NZ privacy compliance',
      icon: 'Shield',
    },
  ],

  screenshots: [
    {
      src: '/images/landing-page/qr-scan-mobile.png',
      caption: 'QR scan prompt & mobile UI',
      alt: 'Mobile interface showing QR code scanning for ClinicPro',
    },
    {
      src: '/images/landing-page/transcript-collapsed.png',
      caption: 'Collapsed transcript bar + warning badge',
      alt: 'Collapsed transcript interface with notification badges',
    },
    {
      src: '/images/landing-page/transcript-expanded.png',
      caption: 'Expanded live transcript',
      alt: 'Live transcription interface showing real-time speech-to-text',
    },
    {
      src: '/images/landing-page/final-note.png',
      caption: 'Final formatted note',
      alt: 'Final structured SOAP note generated by ClinicPro',
    },
  ],

  founder: {
    name: 'Dr Ryo Eguchi',
    title: 'Founder & Practising GP',
    quote: 'I\'m Dr Ryo Eguchi; I\'ve been where you are. Spending hours after work just trying to catch up on notes, feeling like I wasn\'t fully present with my patients because I was thinking about documentation. ClinicPro is the solution I built for us.',
    image: '/images/landing-page/DrRyoEguchiProfilePicMain.jpg',
  },

  roadmap: [
    { milestone: 'Beta Launch', quarter: 'Q3 \'25', status: 'current' },
    { milestone: 'EMR Integration', quarter: 'Q3 \'25', status: 'planned' },
    { milestone: 'Advanced Analytics', quarter: 'Q3 \'25', status: 'planned' },
  ],

  pricing: {
    tiers: [
      {
        name: 'Founder\'s Price',
        subtitle: 'GPs 1–30',
        price: 30,
        originalPrice: 89,
        savings: 66,
        featured: true,
      },
      {
        name: 'Early Adopter',
        subtitle: 'GPs 31–100',
        price: 49,
        originalPrice: 89,
        savings: 45,
        featured: false,
      },
      {
        name: 'Standard',
        subtitle: 'After 100',
        price: 89,
        originalPrice: null,
        savings: 0,
        featured: false,
      },
    ],
    guarantee: 'Launch rate guaranteed for 12 months',
    cta: 'Secure Your Early Adopter Spot – Limited to First 100 GPs!',
  },

  faqs: [
    {
      question: 'What devices does ClinicPro work with?',
      answer: 'ClinicPro works on any device with a web browser. You can use your computer, tablet, or smartphone. The mobile recording feature works on both iOS and Android devices.',
    },
    {
      question: 'How do I get patient consent for recording?',
      answer: 'ClinicPro includes a simple consent process built into the workflow. Patients can provide verbal consent which is recorded, or you can use our digital consent form on your device.',
    },
    {
      question: 'Can I edit the transcripts and notes?',
      answer: 'Absolutely! You have complete control over all generated content. You can edit transcripts, modify notes, and approve everything before it\'s finalised.',
    },
    {
      question: 'What if I\'m not in the first 30 spots?',
      answer: 'Don\'t worry! Even if you miss the first 30, early adopters (positions 31-100) still get significant savings at NZ$49/month instead of the standard NZ$89/month.',
    },
    {
      question: 'Is there a long-term commitment required?',
      answer: 'No long-term contracts required. You can cancel anytime. However, your early adopter pricing is guaranteed for 12 months from launch.',
    },
    {
      question: 'Is the pricing locked in?',
      answer: 'Yes! Your early adopter rate is guaranteed for 12 months. After that, you\'ll have advance notice of any pricing changes.',
    },
    {
      question: 'Does the price include GST?',
      answer: 'Yes, all prices shown include GST. No hidden fees or surprise charges.',
    },
  ],
};

export const formatNZD = (amount: number): string => {
  return new Intl.NumberFormat('en-NZ', {
    style: 'currency',
    currency: 'NZD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};
