'use client';

import { ChevronLeft, ChevronRight, Eye, FileCheck, MousePointer, Smartphone } from 'lucide-react';
import Image from 'next/image';
import { useState } from 'react';

export const ScreenshotGallery = () => {
  const [currentIndex, setCurrentIndex] = useState(0);

  // Using available images as placeholders for the specified screenshots
  const screenshots = [
    {
      src: '/images/landing-page/hero-image.png',
      caption: 'QR scan prompt & mobile UI',
      alt: 'Mobile interface showing QR code scanning for ClinicPro',
      icon: Smartphone,
      color: 'nz-green',
    },
    {
      src: '/images/landing-page/hero-image.png', // Placeholder - would be transcript-collapsed.png
      caption: 'Collapsed transcript bar + warning badge',
      alt: 'Collapsed transcript interface with notification badges',
      icon: Eye,
      color: 'nz-blue',
    },
    {
      src: '/images/landing-page/hero-image.png', // Placeholder - would be transcript-expanded.png
      caption: 'Expanded live transcript',
      alt: 'Live transcription interface showing real-time speech-to-text',
      icon: MousePointer,
      color: 'purple',
    },
    {
      src: '/images/landing-page/hero-image.png', // Placeholder - would be final-note.png
      caption: 'Final formatted note',
      alt: 'Final structured SOAP note generated by ClinicPro',
      icon: FileCheck,
      color: 'nz-green',
    },
  ];

  const nextSlide = () => {
    setCurrentIndex(prev => (prev + 1) % screenshots.length);
  };

  const prevSlide = () => {
    setCurrentIndex(prev => (prev - 1 + screenshots.length) % screenshots.length);
  };

  const currentScreenshot = screenshots[currentIndex];
  if (!currentScreenshot) {
    return null;
  }

  return (
    <section className="relative bg-white py-16 sm:py-24 lg:py-32">
      {/* Background Elements */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="to-nz-green-300/8 absolute -right-40 top-20 size-[500px] rounded-full bg-gradient-to-br from-nz-blue-200/10 blur-3xl"></div>
        <div className="from-nz-green-200/8 absolute -left-60 bottom-32 size-[600px] rounded-full bg-gradient-to-tr to-nz-blue-300/10 blur-3xl"></div>
      </div>

      <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-16 text-center">
          <h2 className="mb-6 text-3xl font-bold text-gray-900 sm:text-4xl lg:text-5xl">
            See ClinicPro in Action
          </h2>
          <p className="mx-auto max-w-2xl text-lg text-gray-600 sm:text-xl">
            From mobile recording to final notes—watch how simple GP documentation can be
          </p>
        </div>

        {/* Gallery */}
        <div className="relative">
          {/* Main Image Display */}
          <div className="relative mx-auto max-w-4xl">
            <div className="aspect-[16/10] overflow-hidden rounded-2xl bg-gradient-to-br from-gray-50 to-nz-blue-50 shadow-2xl">
              <Image
                src={currentScreenshot.src}
                alt={currentScreenshot.alt}
                fill
                className="object-cover transition-all duration-500"
              />

              {/* Overlay with current step info */}
              <div className="absolute inset-0 bg-gradient-to-t from-black/20 via-transparent to-transparent">
                <div className="absolute bottom-4 left-4 sm:bottom-6 sm:left-6">
                  <div className="rounded-xl border border-white/30 bg-white/90 px-4 py-3 backdrop-blur-sm">
                    <div className="flex items-center gap-3">
                      <div className={
                        currentScreenshot.color === 'nz-green'
                          ? 'flex size-8 items-center justify-center rounded-lg bg-nz-green-100'
                          : currentScreenshot.color === 'nz-blue'
                            ? 'flex size-8 items-center justify-center rounded-lg bg-nz-blue-100'
                            : 'flex size-8 items-center justify-center rounded-lg bg-purple-100'
                      }
                      >
                        {(() => {
                          const IconComponent = currentScreenshot.icon;
                          return (
                            <IconComponent className={
                              currentScreenshot.color === 'nz-green'
                                ? 'size-4 text-nz-green-600'
                                : currentScreenshot.color === 'nz-blue'
                                  ? 'size-4 text-nz-blue-600'
                                  : 'size-4 text-purple-600'
                            }
                            />
                          );
                        })()}
                      </div>
                      <div>
                        <div className="text-sm font-semibold text-gray-900">
                          Step
                          {' '}
                          {currentIndex + 1}
                          {' '}
                          of
                          {' '}
                          {screenshots.length}
                        </div>
                        <div className="text-xs text-gray-600">
                          {currentScreenshot.caption}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Hotspot tooltips - positioned as examples */}
              {currentIndex === 0 && (
                <div className="absolute right-1/4 top-1/3">
                  <div className="relative">
                    <div className="size-4 animate-pulse rounded-full bg-nz-green-500 shadow-lg"></div>
                    <div className="absolute -top-12 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-lg bg-gray-900 px-3 py-1 text-xs text-white shadow-lg">
                      Tap to start recording
                    </div>
                  </div>
                </div>
              )}

              {currentIndex === 2 && (
                <>
                  <div className="absolute left-1/4 top-1/2">
                    <div className="relative">
                      <div className="size-4 animate-pulse rounded-full bg-nz-blue-500 shadow-lg"></div>
                      <div className="absolute -top-12 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-lg bg-gray-900 px-3 py-1 text-xs text-white shadow-lg">
                        Live transcription
                      </div>
                    </div>
                  </div>
                  <div className="absolute bottom-1/3 right-1/3">
                    <div className="relative">
                      <div className="size-4 animate-pulse rounded-full bg-purple-500 shadow-lg"></div>
                      <div className="absolute -bottom-12 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-lg bg-gray-900 px-3 py-1 text-xs text-white shadow-lg">
                        AI processing
                      </div>
                    </div>
                  </div>
                </>
              )}
            </div>

            {/* Navigation Buttons */}
            <button
              onClick={prevSlide}
              className="absolute left-2 top-1/2 flex size-12 -translate-y-1/2 items-center justify-center rounded-full bg-white/90 shadow-lg transition-all duration-200 hover:scale-110 hover:bg-white sm:left-4"
              aria-label="Previous screenshot"
            >
              <ChevronLeft className="size-6 text-gray-700" />
            </button>

            <button
              onClick={nextSlide}
              className="absolute right-2 top-1/2 flex size-12 -translate-y-1/2 items-center justify-center rounded-full bg-white/90 shadow-lg transition-all duration-200 hover:scale-110 hover:bg-white sm:right-4"
              aria-label="Next screenshot"
            >
              <ChevronRight className="size-6 text-gray-700" />
            </button>
          </div>

          {/* Thumbnail Navigation */}
          <div className="mt-8 flex justify-center">
            <div className="flex space-x-4">
              {screenshots.map((screenshot, index) => (
                <button
                  key={index}
                  onClick={() => setCurrentIndex(index)}
                  className={`relative overflow-hidden rounded-lg transition-all duration-200 ${
                    index === currentIndex
                      ? 'scale-110 ring-2 ring-nz-green-500'
                      : 'opacity-70 hover:scale-105 hover:opacity-100'
                  }`}
                >
                  <div className="size-16 sm:size-20">
                    <Image
                      src={screenshot.src}
                      alt={`Thumbnail ${index + 1}`}
                      fill
                      className="object-cover"
                    />
                    {index === currentIndex && (
                      <div className="absolute inset-0 bg-nz-green-500/20"></div>
                    )}
                  </div>

                  {/* Step indicator */}
                  <div className="absolute -bottom-1 -right-1 flex size-6 items-center justify-center rounded-full bg-nz-green-600 text-xs font-bold text-white">
                    {index + 1}
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Caption */}
          <div className="mt-6 text-center">
            <figcaption className="text-lg font-medium text-gray-700">
              {currentScreenshot.caption}
            </figcaption>
            <p className="mt-2 text-sm text-gray-500">
              {currentScreenshot.alt}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};
