import OpenAI from 'openai';

import { MODEL_CONFIGS } from '@/config/openai-config';

export class AIProcessingService {
  private static instance: AIProcessingService;
  private openai: OpenAI;

  private constructor() {
    this.openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
  }

  public static getInstance(): AIProcessingService {
    if (!AIProcessingService.instance) {
      AIProcessingService.instance = new AIProcessingService();
    }
    return AIProcessingService.instance;
  }

  async processContent(
    prompt: string,
    variables: Record<string, any>,
    maxTokens: number = MODEL_CONFIGS.noteGeneration.max_tokens,
  ): Promise<string> {
    try {
      const enhancedPrompt = this.enhancePromptWithVariables(prompt, variables);

      const response = await this.openai.chat.completions.create({
        model: MODEL_CONFIGS.noteGeneration.model,
        messages: [
          {
            role: 'system',
            content: 'You are a medical documentation assistant with expertise in clinical note generation. Maintain professional medical terminology and follow HIPAA guidelines.',
          },
          {
            role: 'user',
            content: enhancedPrompt,
          },
        ],
        max_tokens: maxTokens,
        temperature: MODEL_CONFIGS.noteGeneration.temperature,
        top_p: 0.8,
        frequency_penalty: 0.3,
        presence_penalty: 0.2,
      });

      const generatedContent = response.choices[0]?.message?.content?.trim();

      if (!generatedContent) {
        throw new Error('No content generated by AI');
      }

      return this.postProcessContent(generatedContent);
    } catch (error: unknown) {
      console.error('AI processing error:', error);
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      throw new Error(`AI processing failed: ${errorMessage}`);
    }
  }

  private enhancePromptWithVariables(
    prompt: string,
    variables: Record<string, any>,
  ): string {
    const variableContext = Object.entries(variables)
      .map(([key, value]) => `${key}: ${value}`)
      .join('\n');

    return `
${prompt}

Context Variables:
${variableContext}

Instructions:
- Use the provided variables in the generated content where appropriate
- Maintain professional medical terminology
- Follow HIPAA compliance guidelines
- Structure the content clearly and logically
- Be specific and precise in medical descriptions
- Include relevant clinical correlations
`;
  }

  private postProcessContent(content: string): string {
    return content
      // Remove any potential PII patterns
      .replace(/\b\d{3}-\d{2}-\d{4}\b/g, '[SSN REDACTED]')
      .replace(/\b\d{10}\b/g, '[MRN REDACTED]')
      // Standardize medical abbreviations
      .replace(/\b([A-Z]{2,})\b/g, (match) => {
        const commonAbbreviations: Record<string, string> = {
          BP: 'blood pressure',
          HR: 'heart rate',
          RR: 'respiratory rate',
          // Add more common abbreviations as needed
        };
        return commonAbbreviations[match] || match;
      })
      // Ensure proper formatting
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  }
}
